default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ashu@855496
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: todo_app_development


test:
  <<: *default
  database: todo_app_test


production:
  <<: *default
  database: todo_app_production
  username: todo_app
  password: <%= ENV['PROJECTNAME_DATABASE_PASSWORD'] %>


 